// Chris Joakim, Microsoft, 2018/11/21

const express = require('express');
const router  = express.Router();
// The build_timestamp.json file is generated by Grunt
const build_timestamp_obj = require("../build_timestamp.json");

var azu = require('../lib/azu');

var opts = {};
opts['queue_name'] = 'outbound';
opts['key_name']   = process.env.AZURE_SERVICEBUS_KEY_NAME;
opts['key_value']  = process.env.AZURE_SERVICEBUS_ACCESS_KEY;
console.log(opts);
var sbu = new azu.AzuSvcBusUtil(opts);

router.get('/ping', function(req, res) {
  var now = new Date();
  var message = {};
  var body = {};
  var svcbus_session_id = req.app.locals.svcbus_session_id;

  body['text'] = 'test message ' + now.getTime();
  body['date'] = now;
  body['epoch'] = now.getTime();
  body['pid'] = req.app.locals.pid;
  body['ENV'] = req.app.locals.ENV;
  body['start_date'] = req.app.locals.start_date;
  body['start_epoch'] = req.app.locals.start_epoch;
  body['svcbus_session_id'] = svcbus_session_id;
  message.body = JSON.stringify(body);
  message.brokerProperties = {};
  message.brokerProperties['SessionId'] = svcbus_session_id;
  message.brokerProperties['ReplyToSessionId'] = svcbus_session_id;

  sbu.on('done', (evt_obj) => {
      console.log(JSON.stringify(evt_obj, null, 2));
  });
  sbu.send_message_to_queue(message, 'inbound');
  res.json(message);
});

module.exports = router;
