// Chris Joakim, Microsoft, 2018/11/21

const express = require('express');
const router  = express.Router();
const process = require('process');

const start_date  = new Date();
const start_epoch = start_date.getTime();
const pid = process.pid;
const session_id = 'session-' + pid + '-' + start_epoch;

// The build_timestamp.json file is generated by Grunt
const build_timestamp_obj = require("../build_timestamp.json");

var azu = require('../lib/azu');

var opts = {};
opts['queue_name'] = 'outbound';
opts['key_name']   = process.env.AZURE_SERVICEBUS_KEY_NAME;
opts['key_value']  = process.env.AZURE_SERVICEBUS_ACCESS_KEY;
console.log(opts);
var sbu = new azu.AzuSvcBusUtil(opts);

router.get('/ping', function(req, res) {
  var now = new Date();
  var message = {};
  var body = {};
  body['text'] = 'test message ' + now.getTime();
  body['date'] = now;
  body['epoch'] = now.getTime();
  body['start_date'] = start_date;
  body['start_epoch'] = start_epoch;
  body['session_id'] = session_id;
  message.body = JSON.stringify(body);
  message.brokerProperties = {};
  message.brokerProperties['SessionId'] = session_id;
  message.brokerProperties['ReplyToSessionId'] = session_id;

  sbu.on('done', (evt_obj) => {
      console.log(JSON.stringify(evt_obj, null, 2));
  });
  sbu.send_message_to_queue(message, 'inbound');
  res.json(message);
});

module.exports = router;
