// Chris Joakim, Microsoft, 2018/11/21

const express = require('express');
const router  = express.Router();
const process = require('process');
const pid = process.pid;

// The build_timestamp.json file is generated by Grunt
const build_timestamp_obj = require("../build_timestamp.json");

var azu = require('../lib/azu');

var opts = {};
opts['queue_name'] = 'outbound';
opts['key_name']   = process.env.AZURE_SERVICEBUS_KEY_NAME;
opts['key_value']  = process.env.AZURE_SERVICEBUS_ACCESS_KEY;
console.log(opts);
var sbu = new azu.AzuSvcBusUtil(opts);

router.get('/ping', function(req, res) {
  var date = new Date();
  var message = {};
  var body = {};
  body['text'] = 'test message';
  body['date'] = date;
  body['epoch'] = date.getTime();
  message.body = JSON.stringify(body);
  message.brokerProperties = {};
  message.brokerProperties['SessionId'] = pid;
  message.brokerProperties['ReplyToSessionId'] = pid;

  sbu.on('done', (evt_obj) => {
      console.log(JSON.stringify(evt_obj, null, 2));
  });
  //console.log('sending msg: ' + JSON.stringify(message, null, 2));
  sbu.send_message_to_queue(message, 'inbound');

  res.json(message);
});

module.exports = router;
